"""cria tabela agendamentos

Revision ID: bfcbb0022d0a
Revises: e138229e8566
Create Date: 2026-06-05 17:31:36.240796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcbb0022d0a'
down_revision = 'e138229e8566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamento')
    op.drop_table('servico')
    # ### end Alembic commands ###
